export const TIPOS = {
  seleccion_clasica: {
    label: 'La Selección Clásica',
    emoji: '🎯',
    desc: 'Opción múltiple · 4 respuestas',
    colorBorder: 'border-brandPrimary',
    colorBadge: 'bg-brandPrimary/10 text-brandPrimary',
    crear: () => ({
      tipo: 'seleccion_clasica',
      pregunta: '',
      opciones: ['', '', '', ''],
      correcta: 0,
    }),
  },
  verdad_mito: {
    label: 'Verdad o Mito',
    emoji: '⚖️',
    desc: 'Enunciado verdadero o falso con justificación',
    colorBorder: 'border-brandSuccess',
    colorBadge: 'bg-brandSuccess/10 text-brandSuccess',
    crear: () => ({
      tipo: 'verdad_mito',
      enunciado: '',
      correcto: 'verdad',
      explicacion: '',
    }),
  },
  rompecabezas_ideas: {
    label: 'Rompecabezas de Ideas',
    emoji: '🧩',
    desc: 'Ordena 4 fragmentos en la secuencia correcta',
    colorBorder: 'border-purple-500',
    colorBadge: 'bg-purple-100 text-purple-700',
    crear: () => ({
      tipo: 'rompecabezas_ideas',
      instruccion: '',
      fragmentos: ['', '', '', ''],
    }),
  },
  parejas_logicas: {
    label: 'Parejas Lógicas',
    emoji: '🔗',
    desc: 'Empareja 4 conceptos con sus definiciones',
    colorBorder: 'border-orange-500',
    colorBadge: 'bg-orange-100 text-orange-700',
    crear: () => ({
      tipo: 'parejas_logicas',
      instruccion: '',
      pares: [
        { izquierda: '', derecha: '' },
        { izquierda: '', derecha: '' },
        { izquierda: '', derecha: '' },
        { izquierda: '', derecha: '' },
      ],
    }),
  },
  caza_intruso: {
    label: 'Caza el Intruso',
    emoji: '🔍',
    desc: 'Encuentra el elemento que no pertenece al grupo',
    colorBorder: 'border-brandDanger',
    colorBadge: 'bg-red-100 text-red-700',
    crear: () => ({
      tipo: 'caza_intruso',
      instruccion: '',
      elementos: ['', '', '', '', ''],
      intruso_idx: 0,
    }),
  },
  clasificador: {
    label: 'El Clasificador',
    emoji: '📂',
    desc: 'Clasifica elementos en dos categorías',
    colorBorder: 'border-teal-500',
    colorBadge: 'bg-teal-100 text-teal-700',
    crear: () => ({
      tipo: 'clasificador',
      instruccion: '',
      categorias: [
        { nombre: '', items: ['', '', ''] },
        { nombre: '', items: ['', '', ''] },
      ],
    }),
  },
  palabras_perdidas: {
    label: 'Palabras Perdidas',
    emoji: '✍️',
    desc: 'Completa el texto con el banco de palabras',
    colorBorder: 'border-indigo-500',
    colorBadge: 'bg-indigo-100 text-indigo-700',
    crear: () => ({
      tipo: 'palabras_perdidas',
      oracion: '',
      banco: ['', '', '', ''],
      respuestas: [''],
    }),
  },
  paso_a_paso: {
    label: 'Paso a Paso',
    emoji: '📋',
    desc: 'Ordena los pasos de un proceso en secuencia',
    colorBorder: 'border-amber-500',
    colorBadge: 'bg-amber-100 text-amber-700',
    crear: () => ({
      tipo: 'paso_a_paso',
      instruccion: '',
      pasos: ['', '', '', ''],
    }),
  },
  real_inventado: {
    label: 'Real o Inventado',
    emoji: '🎭',
    desc: '¿Hecho comprobado o ficción?',
    colorBorder: 'border-pink-500',
    colorBadge: 'bg-pink-100 text-pink-700',
    crear: () => ({
      tipo: 'real_inventado',
      enunciado: '',
      correcto: 'real',
      explicacion: '',
    }),
  },
  detective_texto: {
    label: 'Detective de Texto',
    emoji: '🕵️',
    desc: 'Lee el pasaje y responde la pregunta',
    colorBorder: 'border-slate-500',
    colorBadge: 'bg-slate-100 text-slate-700',
    crear: () => ({
      tipo: 'detective_texto',
      pasaje: '',
      pregunta: '',
      opciones: ['', '', '', ''],
      correcta: 0,
    }),
  },
};

export const TIPOS_LISTA = Object.entries(TIPOS).map(([key, val]) => ({ key, ...val }));
